stages:
        - evaluate
        - gitlabci-test-a
        - gitlabci-test-b

evaluate:
        stage: evaluate
        script:
                - export tag_name=$(sed -e 's|/|_|g' <<< $CI_COMMIT_REF_NAME)                       
                - echo "tag_name=$tag_name" >> build.env
        artifacts:
                reports:
                        dotenv: build.env                               

gitlabci-test-a:
        stage: gitlabci-test-a
        tags:
                - docker
                - lower-privacy
                - meta
                - ubuntu
        script :
                - echo "hello-world" >> hw.carbon
                - env >> build.env
        artifacts:
                reports:
                        dotenv: build.env
                expire_in: 1 week

                        
gitlabci-test-b:
        stage: gitlabci-test-b
        script :
                - echo "hello-world" >> hw.carbon
                - env >> other.env
        artifacts:
                reports:
                        dotenv: other.env
                expire_in: 1 hour
