# vim: set ts=2 sts=2 sw=2 expandtab ruler:
stages:
  - docker_base

docker-base:
  stage: docker_base
  image: docker:19.03.12
  services:
     - docker:19.03.12-dind
  tags:
     - lower-privacy
     - docker
     - ubuntu
     - meta
  script:
     - export IMAGE_NAME=$CI_REGISTRY_IMAGE
     - cd baseline
     - export TEST=$(./docker-build.sh centos7 --get-image-name)
     - echo "IMAGE_NAME = $IMAGE_NAME" >> /tmp/info.txt
     - echo "TEST = $TEST" >> /tmp/info.txt
     - #docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
     - #cd baseline && docker-build.sh centos7
     - #docker push $IMAGE_NAME
  only:
     variables:
       - $DOCKER_BASE
  artifacts:
    paths:
      - /tmp/info.txt   
  allow_failure: true
